---
title: "Assignment_2"
author: "Max Russer"
date: "April 25, 2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message = FALSE}

#load packages and read in data

library(tidyverse)
library(ggplot2)

gas <- read_csv("Gas_Data.csv")
```

```{r}

#Part 1. 

#complete linear regression to find demand equations

#low demand 

low_demandlm <- lm(Price_Dollars ~ Q_Low_Gallons_per_Day, data = gas)

low_demandlm

#high demand

high_demandlm <- lm(Price_Dollars ~ Q_High_Gallons_per_Day, data = gas)

high_demandlm



```

Problems 1 and 2:

1. 

CS: 2365526.93
PS: 667984.0293
EC: 534387.2234

2. 

CS(low): 1065273.429
CS(high): 1303951.933

```{r}
#define functions and plot

Q_low <- function(x) 21.9908534 - 0.0001355 * x
Q_high <- function(x) 23.3914418 - 0.0001297 * x
Q_ag <- function(x) 22.70646323 - 0.000066268 * x
supply <- function(x) x * .000018713
mec <- function(x) 2

status_quo <- ggplot(data.frame(x = c(70000, 500000), y = c(0, 30)), aes(x = x, y = y)) +
  stat_function(fun = Q_low, geom = "line", color = "blue") +
  stat_function(fun = Q_high, geom = "line", color = "green") +
  stat_function(fun = Q_ag, geom = "line", color = "black") +
  stat_function(fun = supply, geom = "line", color = "brown") +
  stat_function(fun = mec, geom = "line", color = "red") +
  scale_x_continuous(expand = c(0,0), limits = c(0,400000)) +
  scale_y_continuous(expand = c(0,0), limits = c(0,25)) +
  labs(x = "Quantity (gallons)", y = "Price (dollars)") +
  theme_light()

status_quo


```

Problem 3:

amount produced and sold: 261310.9193
price of gasoline: $5.39
CS(low): 1016931.12
CS(high): 1249236.341
PS: 638905.1977
EC:522621.8386
total revenue generated by tax: 130655.4597


```{r}
#define the functions and plot

Q_low <- function(x) 21.9908534 - 0.0001355 * x
Q_high <- function(x) 23.3914418 - 0.0001297 * x
Q_ag <- function(x) 22.70646323 - 0.000066268 * x
supply_tax1 <- function(x) .50 + x * .000018713
mec <- function(x) 2

tax_3 <- ggplot(data.frame(x = c(70000, 500000), y = c(0, 30)), aes(x = x, y = y)) +
  stat_function(fun = Q_low, geom = "line", color = "blue") +
  stat_function(fun = Q_high, geom = "line", color = "green") +
  stat_function(fun = Q_ag, geom = "line", color = "black") +
  stat_function(fun = supply_tax1, geom = "line", color = "brown") +
  stat_function(fun = mec, geom = "line", color = "red") +
  scale_x_continuous(expand = c(0,0), limits = c(0,400000)) +
  scale_y_continuous(expand = c(0,0), limits = c(0,25)) +
  labs(x = "Quantity (gallons)", y = "Price (dollars)") +
  theme_light()

tax_3


```

Problem 4:

$0 tax

CS(low): 530886.2056
CS(high) and PS same as problem 1

$1 tax

CS(low): 458856.8192
CS(high):
PS:

```{r warning=FALSE}
#$1 tax 

#define the functions and plot

Q_low <- function(x) 21.9908534 - 0.0001355 * x
Q_high <- function(x) 23.3914418 - 0.0001297 * x
Q_ag <- function(x) 22.70646323 - 0.000066268 * x
supply_tax4_1 <- function(x) 1 + x * .000018713
mec <- function(x) 2

tax4_1 <- ggplot(data.frame(x = c(70000, 500000), y = c(0, 30)), aes(x = x, y = y)) +
  stat_function(fun = Q_low, geom = "line", color = "blue") +
  stat_function(fun = Q_high, geom = "line", color = "green") +
  stat_function(fun = Q_ag, geom = "line", color = "black") +
  stat_function(fun = supply_tax4_1, geom = "line", color = "brown") +
  stat_function(fun = mec, geom = "line", color = "red") +
  scale_x_continuous(expand = c(0,0), limits = c(0,400000)) +
  scale_y_continuous(expand = c(0,0), limits = c(0,25)) +
  labs(x = "Quantity (gallons)", y = "Price (dollars)") +
  theme_light()

tax4_1
```




